// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:fdeb5c79-abdb-426a-b854-271a8a6a5635",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_HkQwCXfW2",
    "aws_user_pools_web_client_id": "1becqv2plj9fj8u3q2hure7dvu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rwsklerz4fbb5hhtmkcj5m5amq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "amplify-notetaker-20190619235030-hostingbucket-noteenv",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://amplify-notetaker-20190619235030-hostingbucket-noteenv.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
